export enum TokenType {
  var = 'var',
  integer = 'integer',
  real = 'real',
  string = 'string',
  begin = 'begin',
  end = 'end',
  repeat = 'repeat',
  until = 'until',
  comma = ',',
  dot = '.',
  colon = ':',
  semicolon = ';',
  gt = '>',
  lt = '<',
  equals = '=',
  lpar = '(',
  rpar = ')',
  plus = '+',
  minus = '-',
  multy = '*',
  delimiter = '/',
  id = 'id',
  literal = 'literal',
}
